### ISSUE TITLE
Strip reddit markdown when displaying username

### ISSUE THREAD

**Issue by nathaniel-ortiz** [thelectronicnub/redditswapbot#17]
Strip the reddit markdown when displaying the user's username in the user information comment

**Comment by Chankster** [comment]
Example?

**Comment by nathaniel-ortiz** [comment]
https://www.reddit.com/r/mechmarket/comments/3y0zvf/us_ca_h_carbon_base_kit_novelties_kit_w_hackd_by/

**Comment by nathaniel-ortiz** [comment]
Merged praw5 branch, issue closed.
