### ISSUE TITLE
Stop using 'i-' flair prefixes

### ISSUE THREAD

**Issue by Chankster** [thelectronicnub/redditswapbot#19]
It's completely unnecessary.  Flairs should be the number only.

**Comment by nathaniel-ortiz** [comment]
I don't moderate mechmarket anymore, but I'll be sure to let them know.

It was required to do the convulted flair animations at the time, I haven't looked at the CSS in quite a while

**Comment by soilheart** [comment]
I suck at CSS, and have no clue why the "i"s are there, and would not complain if we could get rid of them. Would require some work on migrating the current flairs to without an i (or require our already large CSS to expand -_-) though.

So as a first step I would propose making flair prefix a setting (with no prefix as default setting).

**Comment by Chankster** [comment]
I'll probably just end up committing all the code to remove the 'i-' prefix (as its how the original code was written).  If you want to continue using 'i-' flairs just don't update past that commit.

**Comment by soilheart** [comment]
I'd appreciate if you kept the commit self-contained in that case, so I can revert it locally until we have looked into if we can remove it or not.
