### ISSUE TITLE
Move subreddit specific settings to config

### ISSUE THREAD

**Issue by soilheart** [thelectronicnub/redditswapbot#20]
Move subreddit specific settings to separate config file(s).
Proposed settings:

* Country name list (US/USA, etc.)
* Accepted post tags and their flairs
* User flairs (prefixes, and special user flair, such as vendor on /r/mm)
* ?

**Comment by Chankster** [comment]
Do we want to put the location of the wiki rules as a setting or just move all of the bot replies as separate options.

**Comment by soilheart** [comment]
I would say that everything that either you at hws or funkoswap have manual edits for should be moved to a/the config file (I assume you edit flair.py for the country codes for example).

Mechmarket specific things such as vendor flair and [Artisan] flair should also be moved to a/the config file.

So if you do manual edits to change the wiki path, then maybe the wiki path should be in a/the config file. (The good thing with having the replies general for all subreddits is that it makes formatting easier, as all strings will look the same and not have different fields to fill, which is a headache with most of the python formatting I've worked with).

**Comment by Chankster** [comment]
Got the title regex and rules wiki location moved in https://github.com/thelectronicnub/redditswapbot/commit/7da097566ff8d5f3c3ce07d431865f739d3934ac

I'm thinking for the post link flair and additional title regexes I can handle it via a dict in the config and then iterate over it for checks.

For unique user flairs, I should be able to do a similar thing but with a list to check against.
